### ISSUE TITLE
Support of FORMAT binary (bytea problem)

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#85] opened 2022-11-14 14:51 UTC
- Big `bytea` fields (> a few 100MBs) cannot be exported ([famous old limitation](https://www.postgresql.org/message-id/flat/1836813.YmyOrS99PX%40ronan.dunklau.fr))
- `pg_dumpbinary` uses `COPY ... TO  ... (FORMAT binary)` but has very few features.
- Is it possible that `pg_back` covers this case?  A parameter may contain tables to be dumped with `FORMAT binary`. I suppose that coherence may be a problem (or use  `--snapshot` ?)  And it would need a separate restore script.

**Comment by orgrim** [comment] 2023-01-16 09:20
Hi, sorry for the late reply.

This will make a duplicate of pg_dumpbinary, I don't think it will be of any value. What could be done is allowing to use a different tool than pg_dump to actually dump tables with those big bytea fields.

**Comment by Krysztophe** [comment] 2023-01-16 13:45
pg_dumpbinary as an alternate archiving tool is probably the most elegant way.  It's only a simple script.

**Closed** 2023-08-22 20:12 UTC
